/*
 * generated by Xtext 2.40.0
 */
package org.farhan.dsl.asciidoc.tests;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.resource.Resource.Diagnostic;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.farhan.dsl.asciidoc.asciiDoc.Model;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(AsciiDocInjectorProvider.class)
public class AsciiDocParsingTest {
	@Inject
	private ParseHelper<Model> parseHelper;
	
	@Test
	public void loadModel() throws Exception {
	}
}
