version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - AWS_REGION=us-east-1
      # For local development, you can use AWS credentials
      # - AWS_ACCESS_KEY_ID=your_access_key
      # - AWS_SECRET_ACCESS_KEY=your_secret_key
    volumes:
      - ./logs:/logs
    networks:
      - spring-network

  # Uncomment to use MySQL instead of H2
  # db:
  #   image: mysql:8.0
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=aws_spring_boot
  #     - MYSQL_USER=user
  #     - MYSQL_PASSWORD=password
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   networks:
  #     - spring-network

  # Uncomment to use LocalStack for AWS services simulation
  # localstack:
  #   image: localstack/localstack:latest
  #   ports:
  #     - "4566:4566"
  #   environment:
  #     - SERVICES=s3
  #     - DEBUG=1
  #     - DATA_DIR=/tmp/localstack/data
  #   volumes:
  #     - ./localstack:/tmp/localstack
  #   networks:
  #     - spring-network

networks:
  spring-network:
    driver: bridge

# Uncomment if using MySQL
# volumes:
#   mysql-data:
