apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheep-dog-dev-mcp
  labels:
    app: sheep-dog-dev
spec:
  selector:
    matchLabels:
      app: sheep-dog-dev-mcp
  template:
    metadata:
      labels:
        app: sheep-dog-dev-mcp
    spec:
      containers:
        - name: sheep-dog-dev-mcp
          image: ghcr.io/farhan5248/sheep-dog-dev-mcp:latest
          imagePullPolicy: "Always"
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: LOG_PATH
              value: "/logs"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: logs-volume
              mountPath: /logs
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: logs-volume
          emptyDir: {}