apiVersion: v1
kind: Service
metadata:
  name: sheep-dog-dev-mcp
  labels:
    app: sheep-dog-dev
spec:
  selector:
    app: sheep-dog-dev-mcp
  ports:
    - name: sheep-dog-dev-mcp
      port: 80
      targetPort: 8080
  type: ClusterIP