apiVersion: v1
kind: PersistentVolume
metadata:
  name: sheep-dog-dev-pv
  labels:
    app: sheep-dog-dev
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/sheep-dog-dev"