apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sheep-dog-dev-db-pvc
  labels:
    app: sheep-dog-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi