/*
 * generated by Xtext 2.23.0
 */
package org.farhan.dsl.asciidoc.validation;

import org.eclipse.xtext.validation.Check;
import org.farhan.dsl.asciidoc.asciiDoc.AsciiDocPackage;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class AsciiDocValidator extends AbstractAsciiDocValidator {
	
	public static final String INVALID_NAME = "invalidName";


}
