/*
 * generated by Xtext 2.39.0
 */
package org.farhan.dsl.asciidoc;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AsciiDocRuntimeModule extends AbstractAsciiDocRuntimeModule {
}
