apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheep-dog-aws
  labels:
    app: sheep-dog-aws
spec:
  selector:
    matchLabels:
      app: sheep-dog-aws
  template:
    metadata:
      labels:
        app: sheep-dog-aws
    spec:
      containers:
        - name: sheep-dog-aws
          image: ghcr.io/farhan5248/sheep-dog-aws:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: LOG_LEVEL
              value: "INFO"  # Set to DEBUG to enable debug logging
            - name: LOG_PATH
              value: "/logs"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://sheep-dog-aws-db:3306/greetings
            - name: SPRING_DATASOURCE_USERNAME
              value: greetings
            - name: SPRING_DATASOURCE_PASSWORD
              value: greetings
            - name: SPRING_ARTEMIS_HOST
              value: sheep-dog-aws-artemis
            - name: SPRING_ARTEMIS_PORT
              value: "61616"
            - name: SPRING_ARTEMIS_USER
              value: artemis
            - name: SPRING_ARTEMIS_PASSWORD
              value: artemis
#          volumeMounts:
#            - name: logs-volume
#              mountPath: /logs
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
#      volumes:
#        - name: logs-volume
#          persistentVolumeClaim:
#            claimName: sheep-dog-aws-logs-pvc
