apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sheep-dog-aws-logs-pvc
  labels:
    app: sheep-dog-aws
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
