/*
 * generated by Xtext 2.36.0
 */
package org.farhan.dsl.asciidoc.generator;

import java.io.File;
import org.eclipse.emf.ecore.resource.Resource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.farhan.dsl.asciidoc.asciiDoc.TestStepContainer;
import org.farhan.dsl.asciidoc.asciiDoc.TestSuite;
import org.farhan.dsl.asciidoc.impl.SourceFileRepository;
import org.farhan.dsl.asciidoc.impl.StepObjectImpl;
import org.farhan.dsl.asciidoc.impl.TestProjectImpl;
import org.farhan.dsl.asciidoc.impl.TestStepImpl;
import org.farhan.dsl.lang.StepObjectBuilder;
import org.farhan.dsl.asciidoc.asciiDoc.TestStep;

/**
 * Generates code from your model files on save.
 * 
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
public class AsciiDocGenerator extends AbstractGenerator {

	private static final Logger logger = LoggerFactory.getLogger(AsciiDocGenerator.class);

	@Override
	public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
		logger.debug("Entering doGenerate for resource: {}", resource != null ? resource.getURI() : "null");
		// Automatic generation disabled - use command-based generation instead
		// The reason is that I didn't want to generate code until the user was ready
		// to do so.
		logger.debug("Exiting {}", "doGenerate");
	}

	private static String getName(TestStep eObject) {
		String name = "";
		name += eObject.getStepObjectName() != null ? eObject.getStepObjectName().trim() : "";
		name += eObject.getStepDefinitionName() != null ? " " + eObject.getStepDefinitionName().trim() : "";
		return name;
	}

	public static void generateFromResource(final Resource resource) {
		logger.info("Entering generateFromResource for resource: {}", resource != null ? resource.getURI() : "null");
		try {
			if (resource == null || resource.getContents().isEmpty()) {
				logger.warn("Resource is null or has no contents");
				return;
			}

			if (resource.getContents().get(0) instanceof TestSuite) {
				TestSuite theTestSuite = (TestSuite) resource.getContents().get(0);
				logger.debug("Processing TestSuite: {}", theTestSuite.getName());

				for (TestStepContainer scenario : theTestSuite.getTestStepContainerList()) {
					logger.debug("Processing scenario: {}", scenario.getName());
					for (TestStep step : scenario.getTestStepList()) {
						logger.debug("Processing step: {}", getName(step));
						generateFromTestStep(step, true);
					}
				}
			} else {
				logger.warn("Resource content is not a TestSuite: {}", resource.getContents().get(0).getClass());
			}
			logger.debug("Exiting {}", "generateFromResource");
		} catch (Exception e) {
			logger.error("Failed to generate from resource {}: {}", resource != null ? resource.getURI() : "null",
					e.getMessage(), e);
		}
	}

	public static StepObjectImpl generateFromTestStep(TestStep step, boolean saveToFile) {
		logger.debug("Entering generateFromTestStep for step: {}", step != null ? getName(step) : "null");
		try {
			TestProjectImpl testProject = new TestProjectImpl(
					new SourceFileRepository(
							step.eResource().getURI().toFileString().replace(File.separator, "/")));
			TestStepImpl iTestStep = new TestStepImpl(step);
			iTestStep.getParent().getParent().setParent(testProject);
			StepObjectImpl stepObjectImpl = (StepObjectImpl) StepObjectBuilder
					.generateStepDefinition(iTestStep, testProject).getParent();
			stepObjectImpl.setParent(testProject);
			if (saveToFile) {
				testProject.putStepObject(stepObjectImpl);
			}
			logger.debug("Exiting {}", "generateFromTestStep");
			return stepObjectImpl;
		} catch (Exception e) {
			logger.error("Generation failed for step '{}': {}", step != null ? getName(step) : "null", e.getMessage(),
					e);
		}
		return null;
	}

}
