/*
 * generated by Xtext 2.36.0
 */
package org.farhan.dsl.asciidoc.generator;

import java.io.File;
import org.eclipse.emf.ecore.resource.Resource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.farhan.dsl.asciidoc.asciiDoc.TestStepContainer;
import org.farhan.dsl.asciidoc.asciiDoc.TestSuite;
import org.farhan.dsl.asciidoc.impl.TestStepImpl;
import org.farhan.dsl.lang.ITestProject;
import org.farhan.dsl.lang.SheepDogBuilder;
import org.farhan.dsl.lang.SheepDogFactory;
import org.farhan.dsl.asciidoc.asciiDoc.TestStep;

/**
 * Generates code from your model files on save.
 * 
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
public class AsciiDocGenerator extends AbstractGenerator {

	private static final Logger logger = LoggerFactory.getLogger(AsciiDocGenerator.class);

	@Override
	public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
		logger.debug("Entering doGenerate for resource: {}", resource != null ? resource.getURI() : "null");
		// Automatic generation disabled - use AsciiDocGeneratorCommandService
		// command-based generation instead so that code generation can be triggered
		// on-demand.
		logger.debug("Exiting {}", "doGenerate");
	}

	public static void generateFromResource(final Resource resource) {
		logger.info("Entering generateFromResource for resource: {}", resource != null ? resource.getURI() : "null");
		try {
			if (resource == null || resource.getContents().isEmpty()) {
				logger.warn("Resource is null or has no contents");
				return;
			}

			if (resource.getContents().get(0) instanceof TestSuite) {
				initProject(resource);
				TestSuite theTestSuite = (TestSuite) resource.getContents().get(0);
				logger.debug("Processing TestSuite: {}", theTestSuite.getName());

				for (TestStepContainer scenario : theTestSuite.getTestStepContainerList()) {
					logger.debug("Processing scenario: {}", scenario.getName());
					for (TestStep step : scenario.getTestStepList()) {
						TestStepImpl stepImpl = new TestStepImpl(step);
						logger.debug("Processing step: {}", stepImpl.getName());
						SheepDogBuilder.createTestStepReferencedElements(stepImpl);
					}
				}
			} else {
				logger.warn("Resource content is not a TestSuite: {}", resource.getContents().get(0).getClass());
			}
			logger.debug("Exiting {}", "generateFromResource");
		} catch (Exception e) {
			logger.error("Failed to generate from resource {}: {}", resource != null ? resource.getURI() : "null",
					e.getMessage(), e);
		}
	}

	private static void initProject(Resource resource) {
		ITestProject parent = SheepDogFactory.instance.createTestProject();
		String resourcePath = resource.getURI().toFileString().replace(File.separator, "/");
		String projectPath = resourcePath.split("src/test/resources/asciidoc/specs/")[0].replace("/",
				File.separator);
		parent.setName(new File(projectPath).getAbsolutePath());
	}

}
