name: Publish Sheep Dog Dev Service Maven Plugin Release

on:
  workflow_dispatch:
permissions:
  contents: write
  packages: write

jobs:
  sheep-dog-dev-svc-maven-plugin:
    uses: farhan5248/sheep-dog-ops/.github/workflows/release.yml@main
    with:
      project: 'sheep-dog-dev-svc-maven-plugin'
      plugin: 'Maven'
    secrets: inherit
    
  merge-into-develop:
    needs: [sheep-dog-dev-svc-maven-plugin]
    uses: farhan5248/sheep-dog-ops/.github/workflows/merge.yml@main
    with:
      source: 'main'
      target: 'develop'
    secrets: inherit      